# **2 - Loading**

## Importing Libraries

In [20]:
import numpy as np
import pandas as pd
import pickle

## Reading CSV

In [21]:
fighters = pd.read_csv('./raw_fighter_details.csv', sep = ',')
fights = pd.read_csv('./raw_total_fight_data.csv', sep = ';')

## Overview

In [22]:
print('Fighters Overview')
print('************************************')
print('Shape:', fighters.shape)
print('------------------------------------')
print('Columns:', fighters.columns.values)
print('------------------------------------')
print('Head')
display(fighters.head())
print('------------------------------------')
print('Tail')
display(fighters.tail())

print('------------------------------------')
print('Fights Overview')
print('************************************')
print('Shape:', fights.shape)
print('------------------------------------')
print('Columns:', fights.columns.values)
print('------------------------------------')
print('Head')
display(fights.head())
print('------------------------------------')
print('Tail')
display(fights.tail())

Fighters Overview
************************************
Shape: (3596, 14)
------------------------------------
Columns: ['fighter_name' 'Height' 'Weight' 'Reach' 'Stance' 'DOB' 'SLpM' 'Str_Acc'
 'SApM' 'Str_Def' 'TD_Avg' 'TD_Acc' 'TD_Def' 'Sub_Avg']
------------------------------------
Head

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg
0,Tom Aaron,NaN,155 lbs.,NaN,NaN,"Jul 13, 1978",0.00,0%,0.00,0%,0.00,0%,0%,0.0
1,Papy Abedi,"5' 11""",185 lbs.,NaN,Southpaw,"Jun 30, 1978",2.80,55%,3.15,48%,3.47,57%,50%,1.3
2,Shamil Abdurakhimov,"6' 3""",235 lbs.,"76""",Orthodox,"Sep 02, 1981",2.45,44%,2.45,58%,1.23,24%,47%,0.2
3,Danny Abbadi,"5' 11""",155 lbs.,NaN,Orthodox,"Jul 03, 1983",3.29,38%,4.41,57%,0.00,0%,77%,0.0
4,Hiroyuki Abe,"5' 6""",145 lbs.,NaN,Orthodox,NaN,1.71,36%,3.11,63%,0.00,0%,33%,0.0

------------------------------------
Tail

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg
3591,Zhang Tiequan,"5' 8""",155 lbs.,"69""",Orthodox,"Jul 25, 1978",1.23,36%,2.14,51%,1.95,58%,75%,3.4
3592,Alex Zuniga,NaN,145 lbs.,NaN,NaN,NaN,0.00,0%,0.00,0%,0.00,0%,0%,0.0
3593,George Zuniga,"5' 9""",185 lbs.,NaN,NaN,NaN,7.64,38%,5.45,37%,0.00,0%,100%,0.0
3594,Allan Zuniga,"5' 7""",155 lbs.,"70""",Orthodox,"Apr 04, 1992",3.93,52%,1.80,61%,0.00,0%,57%,1.0
3595,Virgil Zwicker,"6' 2""",205 lbs.,"74""",NaN,"Jun 26, 1982",3.34,48%,4.87,39%,1.31,30%,50%,0.0

------------------------------------
Fights Overview
************************************
Shape: (6012, 41)
------------------------------------
Columns: ['R_fighter' 'B_fighter' 'R_KD' 'B_KD' 'R_SIG_STR.' 'B_SIG_STR.'
 'R_SIG_STR_pct' 'B_SIG_STR_pct' 'R_TOTAL_STR.' 'B_TOTAL_STR.' 'R_TD'
 'B_TD' 'R_TD_pct' 'B_TD_pct' 'R_SUB_ATT' 'B_SUB_ATT' 'R_REV' 'B_REV'
 'R_CTRL' 'B_CTRL' 'R_HEAD' 'B_HEAD' 'R_BODY' 'B_BODY' 'R_LEG' 'B_LEG'
 'R_DISTANCE' 'B_DISTANCE' 'R_CLINCH' 'B_CLINCH' 'R_GROUND' 'B_GROUND'
 'win_by' 'last_round' 'last_round_time' 'Format' 'Referee' 'date'
 'location' 'Fight_type' 'Winner']
------------------------------------
Head

,R_fighter,B_fighter,R_KD,B_KD,R_SIG_STR.,B_SIG_STR.,R_SIG_STR_pct,B_SIG_STR_pct,R_TOTAL_STR.,B_TOTAL_STR.,R_TD,B_TD,R_TD_pct,B_TD_pct,R_SUB_ATT,B_SUB_ATT,R_REV,B_REV,R_CTRL,B_CTRL,R_HEAD,B_HEAD,R_BODY,B_BODY,R_LEG,B_LEG,R_DISTANCE,B_DISTANCE,R_CLINCH,B_CLINCH,R_GROUND,B_GROUND,win_by,last_round,last_round_time,Format,Referee,date,location,Fight_type,Winner
0,Adrian Yanez,Gustavo Lopez,2,0,41 of 103,23 of 51,39%,45%,41 of 103,23 of 51,0 of 0,0 of 1,---,0%,0,0,0,0,0:03,0:00,32 of 83,14 of 40,8 of 19,5 of 7,1 of 1,4 of 4,41 of 102,23 of 51,0 of 0,0 of 0,0 of 1,0 of 0,KO/TKO,3,0:27,3 Rnd (5-5-5),Chris Tognoni,"March 20, 2021","Las Vegas, Nevada, USA",Bantamweight Bout,Adrian Yanez
1,Trevin Giles,Roman Dolidze,0,0,27 of 57,32 of 67,47%,47%,43 of 73,75 of 110,1 of 2,1 of 3,50%,33%,1,2,0,1,1:15,4:15,22 of 51,10 of 37,4 of 4,7 of 14,1 of 2,15 of 16,15 of 42,28 of 59,4 of 5,3 of 6,8 of 10,1 of 2,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Herb Dean,"March 20, 2021","Las Vegas, Nevada, USA",Middleweight Bout,Trevin Giles
2,Tai Tuivasa,Harry Hunsucker,1,0,14 of 18,2 of 6,77%,33%,14 of 18,2 of 6,0 of 0,0 of 0,---,---,0,0,0,0,0:10,0:00,10 of 14,1 of 5,0 of 0,0 of 0,4 of 4,1 of 1,9 of 10,2 of 6,0 of 0,0 of 0,5 of 8,0 of 0,KO/TKO,1,0:49,3 Rnd (5-5-5),Herb Dean,"March 20, 2021","Las Vegas, Nevada, USA",Heavyweight Bout,Tai Tuivasa
3,Cheyanne Buys,Montserrat Conejo,0,0,31 of 65,15 of 41,47%,36%,49 of 87,136 of 168,0 of 0,4 of 5,---,80%,0,2,3,1,1:04,9:53,26 of 60,10 of 35,5 of 5,0 of 1,0 of 0,5 of 5,26 of 56,15 of 41,2 of 2,0 of 0,3 of 7,0 of 0,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Mark Smith,"March 20, 2021","Las Vegas, Nevada, USA",Women's Strawweight Bout,Montserrat Conejo
4,Marion Reneau,Macy Chiasson,0,0,30 of 63,51 of 138,47%,36%,59 of 93,92 of 184,2 of 4,1 of 1,50%,100%,0,0,0,1,2:15,3:48,14 of 40,29 of 110,7 of 13,15 of 20,9 of 10,7 of 8,25 of 54,36 of 119,5 of 9,13 of 15,0 of 0,2 of 4,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Mark Smith,"March 20, 2021","Las Vegas, Nevada, USA",Women's Bantamweight Bout,Macy Chiasson

------------------------------------
Tail

,R_fighter,B_fighter,R_KD,B_KD,R_SIG_STR.,B_SIG_STR.,R_SIG_STR_pct,B_SIG_STR_pct,R_TOTAL_STR.,B_TOTAL_STR.,R_TD,B_TD,R_TD_pct,B_TD_pct,R_SUB_ATT,B_SUB_ATT,R_REV,B_REV,R_CTRL,B_CTRL,R_HEAD,B_HEAD,R_BODY,B_BODY,R_LEG,B_LEG,R_DISTANCE,B_DISTANCE,R_CLINCH,B_CLINCH,R_GROUND,B_GROUND,win_by,last_round,last_round_time,Format,Referee,date,location,Fight_type,Winner
6007,Remco Pardoel,Alberta Cerra Leon,0,0,4 of 6,1 of 3,66%,33%,20 of 22,9 of 11,1 of 1,0 of 0,100%,---,1,0,0,0,--,--,4 of 5,1 of 3,0 of 0,0 of 0,0 of 1,0 of 0,0 of 1,1 of 1,0 of 0,0 of 0,4 of 5,0 of 2,Submission,1,9:51,No Time Limit,John McCarthy,"March 11, 1994","Denver, Colorado, USA",Open Weight Bout,Remco Pardoel
6008,Orlando Wiet,Robert Lucarelli,0,0,8 of 12,2 of 6,66%,33%,11 of 15,2 of 6,0 of 0,1 of 1,---,100%,0,1,0,0,--,--,7 of 11,1 of 2,1 of 1,0 of 1,0 of 0,1 of 3,1 of 3,2 of 6,0 of 0,0 of 0,7 of 9,0 of 0,KO/TKO,1,2:50,No Time Limit,John McCarthy,"March 11, 1994","Denver, Colorado, USA",Open Weight Bout,Orlando Wiet
6009,Johnny Rhodes,David Levicki,0,0,11 of 17,4 of 5,64%,80%,74 of 86,95 of 102,1 of 1,0 of 0,100%,---,0,0,0,0,--,--,9 of 15,4 of 5,1 of 1,0 of 0,1 of 1,0 of 0,1 of 1,1 of 2,1 of 1,2 of 2,9 of 15,1 of 1,KO/TKO,1,12:13,No Time Limit,John McCarthy,"March 11, 1994","Denver, Colorado, USA",Open Weight Bout,Johnny Rhodes
6010,Patrick Smith,Ray Wizard,0,0,1 of 1,1 of 1,100%,100%,1 of 1,2 of 2,0 of 1,0 of 0,0%,---,1,0,0,0,--,--,0 of 0,0 of 0,1 of 1,0 of 0,0 of 0,1 of 1,0 of 0,1 of 1,1 of 1,0 of 0,0 of 0,0 of 0,Submission,1,0:58,No Time Limit,John McCarthy,"March 11, 1994","Denver, Colorado, USA",Open Weight Bout,Patrick Smith
6011,Scott Morris,Sean Daugherty,0,0,1 of 1,0 of 4,100%,0%,2 of 2,1 of 5,1 of 1,0 of 0,100%,---,1,0,0,0,--,--,1 of 1,0 of 2,0 of 0,0 of 0,0 of 0,0 of 2,0 of 0,0 of 3,1 of 1,0 of 1,0 of 0,0 of 0,Submission,1,0:20,No Time Limit,John McCarthy,"March 11, 1994","Denver, Colorado, USA",Open Weight Bout,Scott Morris

## Description

In [23]:
print('Fighters Description')
print('************************************')
display(fighters.info())
print('------------------------------------------------------------------------')
display(fighters.describe(include = ['object']))
display(fighters.describe(include = ['float64']))

print('------------------------------------------------------------------------')
print('Fights Description')
print('************************************')
display(fights.info())
print('------------------------------------------------------------------------')
display(fights.describe(include = ['object']))
display(fights.describe(include = ['int64']))

Fighters Description
************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3596 entries, 0 to 3595
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   fighter_name  3596 non-null   object
 1   Height        3333 non-null   object
 2   Weight        3522 non-null   object
 3   Reach         1684 non-null   object
 4   Stance        2792 non-null   object
 5   DOB           2857 non-null   object
 6   SLpM          3596 non-null   float64
 7   Str_Acc       3596 non-null   object
 8   SApM          3596 non-null   float64
 9   Str_Def       3596 non-null   object
 10  TD_Avg        3596 non-null   float64
 11  TD_Acc        3596 non-null   object
 12  TD_Def        3596 non-null   object
 13  Sub_Avg       3596 non-null   float64
dtypes: float64(4), object(10)
memory usage: 393.4+ KB

None

------------------------------------------------------------------------

,fighter_name,Height,Weight,Reach,Stance,DOB,Str_Acc,Str_Def,TD_Acc,TD_Def
count,3596,3333,3522,1684,2792,2857,3596,3596,3596,3596
unique,3596,26,112,27,5,2438,85,85,83,93
top,Tom Aaron,"6' 0""",170 lbs.,"73""",Orthodox,"Aug 08, 1988",0%,0%,0%,0%
freq,1,405,547,163,2163,4,727,668,1579,1372

              SLpM         SApM       TD_Avg      Sub_Avg
count  3596.000000  3596.000000  3596.000000  3596.000000
mean      2.279633     2.982948     1.211243     0.636707
std       1.901956     2.814008     1.914020     1.566843
min       0.000000     0.000000     0.000000     0.000000
25%       0.700000     1.400000     0.000000     0.000000
50%       2.170000     2.760000     0.510000     0.000000
75%       3.420000     4.002500     1.885000     0.800000
max      19.910000    52.500000    32.140000    21.900000

------------------------------------------------------------------------
Fights Description
************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6012 entries, 0 to 6011
Data columns (total 41 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R_fighter        6012 non-null   object
 1   B_fighter        6012 non-null   object
 2   R_KD             6012 non-null   int64
 3   B_KD             6012 non-null   int64
 4   R_SIG_STR.       6012 non-null   object
 5   B_SIG_STR.       6012 non-null   object
 6   R_SIG_STR_pct    6012 non-null   object
 7   B_SIG_STR_pct    6012 non-null   object
 8   R_TOTAL_STR.     6012 non-null   object
 9   B_TOTAL_STR.     6012 non-null   object
 10  R_TD             6012 non-null   object
 11  B_TD             6012 non-null   object
 12  R_TD_pct         6012 non-null   object
 13  B_TD_pct         6012 non-null   object
 14  R_SUB_ATT        6012 non-null   int64
 15  B_SUB_ATT        6012 non-null   int64
 16  R_REV            6012 non-null   int64
 17  B_REV            6012 non-null   int64
 18  R_CTRL           6012 non-null   object
 19  B_CTRL           6012 non-null   object
 20  R_HEAD           6012 non-null   object
 21  B_HEAD           6012 non-null   object
 22  R_BODY           6012 non-null   object
 23  B_BODY           6012 non-null   object
 24  R_LEG            6012 non-null   object
 25  B_LEG            6012 non-null   object
 26  R_DISTANCE       6012 non-null   object
 27  B_DISTANCE       6012 non-null   object
 28  R_CLINCH         6012 non-null   object
 29  B_CLINCH         6012 non-null   object
 30  R_GROUND         6012 non-null   object
 31  B_GROUND         6012 non-null   object
 32  win_by           6012 non-null   object
 33  last_round       6012 non-null   int64
 34  last_round_time  6012 non-null   object
 35  Format           6012 non-null   object
 36  Referee          5980 non-null   object
 37  date             6012 non-null   object
 38  location         6012 non-null   object
 39  Fight_type       6012 non-null   object
 40  Winner           5902 non-null   object
dtypes: int64(7), object(34)
memory usage: 1.9+ MB

None

------------------------------------------------------------------------

,R_fighter,B_fighter,R_SIG_STR.,B_SIG_STR.,R_SIG_STR_pct,B_SIG_STR_pct,R_TOTAL_STR.,B_TOTAL_STR.,R_TD,B_TD,R_TD_pct,B_TD_pct,R_CTRL,B_CTRL,R_HEAD,B_HEAD,R_BODY,B_BODY,R_LEG,B_LEG,R_DISTANCE,B_DISTANCE,R_CLINCH,B_CLINCH,R_GROUND,B_GROUND,win_by,last_round_time,Format,Referee,date,location,Fight_type,Winner
count,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,6012,5980,6012,6012,6012,5902
unique,1514,1987,3467,3308,97,91,4213,3963,162,159,70,64,748,625,2994,2802,593,573,424,391,2748,2753,498,490,686,501,10,336,19,204,550,166,109,1437
top,Jim Miller,Jeremy Stephens,0 of 0,0 of 0,50%,50%,0 of 0,0 of 1,0 of 0,0 of 0,---,---,0:00,0:00,0 of 0,0 of 0,0 of 0,0 of 0,0 of 0,0 of 0,0 of 0,0 of 0,0 of 0,0 of 0,0 of 0,0 of 0,Decision - Unanimous,5:00,3 Rnd (5-5-5),Herb Dean,"November 19, 2016","Las Vegas, Nevada, USA",Lightweight Bout,Donald Cerrone
freq,27,21,34,52,292,296,24,36,1889,2242,1889,2242,693,1096,64,112,698,816,1252,1250,108,97,1400,1403,1948,2659,2097,2779,5289,858,25,1565,1047,23

,R_KD,B_KD,R_SUB_ATT,B_SUB_ATT,R_REV,B_REV,last_round
count,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000,6012.000000
mean,0.249834,0.179807,0.481371,0.343979,0.137725,0.135396,2.316700
std,0.523408,0.456132,0.924078,0.791808,0.422296,0.414708,1.008284
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
75%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,3.000000
max,5.000000,4.000000,10.000000,7.000000,5.000000,3.000000,5.000000

## Missing  Values

In [24]:
print('Fighters Missing Values')
print('************************************')
for column in fighters.columns:
    print(column, 'Missing Values:', fighters[column].isnull().sum())
    
print('------------------------------------')
print('Fights Missing Values')
print('************************************')
for column in fights.columns:
    print(column, 'Missing Values:', fights[column].isnull().sum())

Fighters Missing Values
************************************
fighter_name Missing Values: 0
Height Missing Values: 263
Weight Missing Values: 74
Reach Missing Values: 1912
Stance Missing Values: 804
DOB Missing Values: 739
SLpM Missing Values: 0
Str_Acc Missing Values: 0
SApM Missing Values: 0
Str_Def Missing Values: 0
TD_Avg Missing Values: 0
TD_Acc Missing Values: 0
TD_Def Missing Values: 0
Sub_Avg Missing Values: 0
------------------------------------
Fights Missing Values
************************************
R_fighter Missing Values: 0
B_fighter Missing Values: 0
R_KD Missing Values: 0
B_KD Missing Values: 0
R_SIG_STR. Missing Values: 0
B_SIG_STR. Missing Values: 0
R_SIG_STR_pct Missing Values: 0
B_SIG_STR_pct Missing Values: 0
R_TOTAL_STR. Missing Values: 0
B_TOTAL_STR. Missing Values: 0
R_TD Missing Values: 0
B_TD Missing Values: 0
R_TD_pct Missing Values: 0
B_TD_pct Missing Values: 0
R_SUB_ATT Missing Values: 0
B_SUB_ATT Missing Values: 0
R_REV Missing Values: 0
B_REV Missing Values: 0
R_CTRL Missing Values: 0
B_CTRL Missing Values: 0
R_HEAD Missing Values: 0
B_HEAD Missing Values: 0
R_BODY Missing Values: 0
B_BODY Missing Values: 0
R_LEG Missing Values: 0
B_LEG Missing Values: 0
R_DISTANCE Missing Values: 0
B_DISTANCE Missing Values: 0
R_CLINCH Missing Values: 0
B_CLINCH Missing Values: 0
R_GROUND Missing Values: 0
B_GROUND Missing Values: 0
win_by Missing Values: 0
last_round Missing Values: 0
last_round_time Missing Values: 0
Format Missing Values: 0
Referee Missing Values: 32
date Missing Values: 0
location Missing Values: 0
Fight_type Missing Values: 0
Winner Missing Values: 110

## Duplicate Values

In [25]:
print(f'Fighters Duplicate Rows: {fighters.duplicated().sum()}')
print(f'Fights Duplicate Rows: {fights.duplicated().sum()}')

Fighters Duplicate Rows: 0
Fights Duplicate Rows: 0

## Unique Values

In [26]:
print('Fighters Unique Values')
print('************************************')
for column in fighters.columns:
    print(column, 'Unique Values:', fighters[column].nunique())
    
print('------------------------------------') 
print('Fights Unique Values')
print('************************************')
for column in fights.columns:
    print(column, 'Unique Values:', fights[column].nunique())

Fighters Unique Values
************************************
fighter_name Unique Values: 3596
Height Unique Values: 26
Weight Unique Values: 112
Reach Unique Values: 27
Stance Unique Values: 5
DOB Unique Values: 2438
SLpM Unique Values: 650
Str_Acc Unique Values: 85
SApM Unique Values: 759
Str_Def Unique Values: 85
TD_Avg Unique Values: 527
TD_Acc Unique Values: 83
TD_Def Unique Values: 93
Sub_Avg Unique Values: 95
------------------------------------
Fights Unique Values
************************************
R_fighter Unique Values: 1514
B_fighter Unique Values: 1987
R_KD Unique Values: 6
B_KD Unique Values: 5
R_SIG_STR. Unique Values: 3467
B_SIG_STR. Unique Values: 3308
R_SIG_STR_pct Unique Values: 97
B_SIG_STR_pct Unique Values: 91
R_TOTAL_STR. Unique Values: 4213
B_TOTAL_STR. Unique Values: 3963
R_TD Unique Values: 162
B_TD Unique Values: 159
R_TD_pct Unique Values: 70
B_TD_pct Unique Values: 64
R_SUB_ATT Unique Values: 11
B_SUB_ATT Unique Values: 8
R_REV Unique Values: 6
B_REV Unique Values: 4
R_CTRL Unique Values: 748
B_CTRL Unique Values: 625
R_HEAD Unique Values: 2994
B_HEAD Unique Values: 2802
R_BODY Unique Values: 593
B_BODY Unique Values: 573
R_LEG Unique Values: 424
B_LEG Unique Values: 391
R_DISTANCE Unique Values: 2748
B_DISTANCE Unique Values: 2753
R_CLINCH Unique Values: 498
B_CLINCH Unique Values: 490
R_GROUND Unique Values: 686
B_GROUND Unique Values: 501
win_by Unique Values: 10
last_round Unique Values: 5
last_round_time Unique Values: 336
Format Unique Values: 19
Referee Unique Values: 204
date Unique Values: 550
location Unique Values: 166
Fight_type Unique Values: 109
Winner Unique Values: 1437

## Exporting Pickles

In [27]:
with open('fighters.pkl', 'wb') as f:
    pickle.dump(fighters, f)
with open('fights.pkl', 'wb') as f:
    pickle.dump(fights, f)